apple/swift-nio-ssh

- docker/Dockerfile
- scripts/generate_docs.sh
- scripts/sanity.sh
Motivation:
Documentation is a real help when using a project, we should be
generating it.
Modifications:
- Ported docs script from SwiftNIO.
Result:
We can provide API documentation.
> Add docs generation script.

- Sources/NIOSSHClient/ExecHandler.swift
- Sources/NIOSSHClient/GlueHandler.swift
- Sources/NIOSSHServer/GlueHandler.swift
Motivation:
When running the example client on extremely low latency connections it
can occasionally stall, printing nothing to stdout before exiting. This
is the result of a timing window where we receive the data before the
pipe bootstrap has been configured and our glue handlers are not in
place.
There is also another timing window where we block reads on the SSH
Child Channel because the glue handler asked if the partner was writable
before the partner was inserted into the pipe channel.
Modifications:
- Cleanup both timing windows.
Result:
The SSH client example will be substantially more reliable.
> Resolve stalls in the example client.

- Sources/NIOSSHClient/ExecHandler.swift
- Sources/NIOSSHClient/PortForwardingServer.swift
- Sources/NIOSSHClient/SimpleCLIParser.swift
- Sources/NIOSSHClient/main.swift
Motivation:
Implementing port forwarding is not always obvious, especially if
you're new to NIO. We should provide some example code.
Modifications:
- Implemented client direct port forwarding example.
Result:
Easier to explain to users what you have to do.
> Implement client port forwarding example.

- Sources/NIOSSH/User Authentication/UserAuthenticationMethod.swift
- Tests/NIOSSHTests/UserAuthenticationStateMachineTests.swift
Motivation:
Right now there is no way to use certified public keys for user auth.
Modifications:
1. Adds new init to PrivateKey
2. Updates UserAuthRequestMessage to support public key
3. Adds a test
Result:
Closes #63
> Implement certified public key client auth

- Sources/NIOSSH/TransportProtection/AESGCM.swift
- docker/docker-compose.yaml
- scripts/soundness.sh
To comply with the new [Swift code of conduct](https://swift.org/code-of-conduct/), let's make the language a little more welcoming.
- Replaced usages of "sanity" with "soundness"
- Added "sanity" to the list of unacceptable terms.
- Changed the CI name to `soundness` to comply with the changes already made by @tomerd: https://github.com/apple/swift-nio/pull/1732#issuecomment-765131877
- Swift NIO SSH is nicer.
> Use welcoming language

- Sources/NIOSSH/Connection State Machine/Operations/AcceptsVersionMessages.swift
- Sources/NIOSSH/Connection State Machine/SSHConnectionStateMachine.swift
- Tests/NIOSSHTests/SSHConnectionStateMachineTests.swift
Motivation:
RFC 4253, section 4.2 allows for server to send some lines before
version in version exchange. Right now we expect that version start with
`SSH-` only. We should support this.
Modifications:
- Modifies version verification to allow clients tolerate lines before
version
- Adds tests that verify that client accepts lines and server doesn't
Result:
Closes #74
> Allows clients tolerate lines before version

- Sources/NIOSSH/Connection State Machine/Operations/AcceptsUserAuthMessages.swift
- Sources/NIOSSH/Connection State Machine/SSHConnectionStateMachine.swift
- Sources/NIOSSH/NIOSSHHandler.swift
- Tests/NIOSSHTests/EndToEndTests.swift
- Tests/NIOSSHTests/SSHConnectionStateMachineTests.swift
Motivation:
Currently there is now way to wait for successful SSH session
establishment, the only way to continue is to try to create a child
channel. Given that most clients are expecting the session to be active
when both key exchange and user authenticaiton complete, I propose to
emit UserAuthSuccessEvent.  That way client can wait for that event or
fail if there is an error in the pipeline.
Modifications:
- Adds UserAuthSuccessEvent event
- Adds .event case to StateMachineInboundProcessResult
- Adds emittion of event if StateMachineInboundProcessResult is .event
- Adds two tests
Result:
Closes #39
> Adds emittion of user authentication success event.

- Package.swift
- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
- Tests/NIOSSHTests/ChildChannelMultiplexerTests.swift
Motivation:
NIO 2.27.0 added a customisation point to `Channel` to allow options to
be fetched synchronously if the caller is on the appropriate event loop.
Modifications:
- Add synchronous options to SSHChildChannel
- Promote event loop assertions to preconditions
Result:
Callers can fetch channel options synchronously on 'SSHChildChannel's.
> Add support from synchronous options

- Sources/NIOSSH/TransportProtection/AESGCM.swift
Motivation:
We should use setContiguousBytes instead of setBytes to avoid hitting
the slow path.
Modifications:
- Use setContiguousBytes.
Result:
Speedy speedy
> Use the ContiguousBytes functions for setting data

- Package.swift
- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
Motivation:
Method Channel.removeHandlers(channel: Channel) was deprecated in 2.32,
we should use recommended method instead.
Modifications:
- Bump swift-nio version to 2.32 to ensue that new methods are
available
- Use new method to remove all handlers
> fixes compilation warning

- Package.swift
Motivation:
Crypto has a very minor breaking change that doesn't affect us, so we
can and should tolerate 1.x and 2.x.
Modifications:
- Widen the pin on Crypto
Result:
We get all the new Crypto goodness.
> Widen the pin on Crypto.

- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
- Tests/NIOSSHTests/ChildChannelMultiplexerTests.swift
- scripts/soundness.sh
Motivation:
When reads have yet to be delivered to a channel and we receive a
CHANNEL_CLOSE message, we forcibly deliver all of the reads. As part of
doing this, we process the window size changes and potentially send
window increment messages. These messages are invalid to send at this
time, and the state machine rightly forbids us from sending them, which
causes a crash.
Modifications:
- Change the code to only futz with the channel window if the channel is
still open.
Result:
No crashing after channel close.
> Fix crash sending window increment after close

- Tests/NIOSSHTests/ChildChannelMultiplexerTests.swift
Motivation:
The recently added test asserted something about the behaviour of the
code that was not true: I was just holding the test wrong.
Modifications:
Fix the test, remove the comment.
Result:
Things are better now
> Clean up incorrect comments and test behaviour

- Sources/NIOSSH/Child Channels/ChildChannelOptions.swift
- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
- Tests/NIOSSHTests/ChildChannelMultiplexerTests.swift
Fixes #99 (see issue for details).
> Add `PeerMaximumMessageLength` option for SSH child channels.

- docker/docker-compose.2004.56.yaml
The 5.6 nightly images are available, let's use them.
@tomerd Can you add a 5.6 builder here?
> Add 5.6 nightly CI.

- Sources/NIOSSH/Connection State Machine/SSHConnectionStateMachine.swift
- Tests/NIOSSHTests/SSHConnectionStateMachineTests.swift
- Tests/NIOSSHTests/Utilities.swift
- Tests/NIOSSHTests/UtilitiesTests.swift
Motivation:
When we call `decodeFirstBlock` we expect that first blockSize bytes,
that include packet length, will be overwritten in the parser buffer
(this is why we pass source byte buffer as inout). This changes state of
the parser, but if we cannot decode a packet we do not return it and in
the connection state machine we return without updating the machine
state. This can lead to calling decodeFirstBlock multiple times until we
have enough data to decode the whole packet in one go.
Modifications:
- Update connection state machine state when active even if we do not
have response message
- Adds TinyEncriptionAlgorithm implementation to test codepaths that
use decodeFirstBlock (unlike AESGCM)
- Test that drip feeds data to parser
> fixes an issue where decodeFirstBlock can be called multiple times

- Sources/NIOSSH/SSHPacketParser.swift
- Tests/NIOSSHTests/SSHPacketParserTests.swift
Connecting to an OpenSSH 7.4 server fails due to that it only uses line
feeds and no carriage returns in the protocol version exchange.
This change makes sure that the identification string is properly
parsed when no carriage returns are present.
Since other clients have no problem connecting to OpenSSH 7.4, not
expecting a carriage return seems to be common. The following
from RFC 4253 also indicates that this is no problem:
"Implementers who wish to maintain compatibility with older,
undocumented versions of this protocol may want to process
the identification string without expecting the presence of
the carriage return character..."
> Support identification string without carriage return

- scripts/check_no_api_breakages.sh
Motivation:
Breaking the API without knowing it would be bad.
Modifications:
Copy over the API breaking script from NIO.
Result:
First part of getting API breakages checked in CI is done.
> Add API breakages script from NIO

- Sources/NIOSSH/Child Channels/ChildChannelOptions.swift
- Sources/NIOSSH/Child Channels/ChildChannelUserEvents.swift
- Sources/NIOSSH/Child Channels/SSHChannelData.swift
- Sources/NIOSSH/Child Channels/SSHChannelType.swift
- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
- Sources/NIOSSH/Keys And Signatures/NIOSSHCertifiedPublicKey.swift
- Sources/NIOSSH/NIOSSHError.swift
- Sources/NIOSSH/NIOSSHSendable.swift
- Sources/NIOSSH/SSHTerminalModes.swift
- scripts/soundness.sh
We need to adopt `Sendable` on certain types that are prone to be shared across threads.
Adopt `Sendable` on some types.
Our types are `Sendable`
> Adopt `Sendable` on our public types

- Package.swift
- Sources/NIOSSH/Child Channels/SSHChannelType.swift
- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
`NIOAtomics` was deprecated in https://github.com/apple/swift-nio/pull/2204 in favor of `swift-atomics` https://github.com/apple/swift-atomics
In addition, the `@preconcrrency` imports of `NIOCore` are not required and do not produce warnings/errors even with the currently latest released version of swift-nio (2.40.0), changes from `main` are not required.
> Use `swift-atomics` instead of `NIOAtomics`

- Sources/NIOSSH/ByteBuffer+SSH.swift
- Sources/NIOSSH/Connection State Machine/SSHConnectionStateMachine.swift
- Sources/NIOSSH/Constants.swift
- Sources/NIOSSH/Key Exchange/SSHKeyExchangeResult.swift
- Sources/NIOSSH/NIOSSHHandler.swift
- Sources/NIOSSH/Role.swift
- Sources/NIOSSH/SSHClientConfiguration.swift
- Sources/NIOSSH/SSHPacketParser.swift
- Sources/NIOSSH/SSHPacketSerializer.swift
- Sources/NIOSSH/SSHServerConfiguration.swift
- Sources/NIOSSH/TransportProtection/AESGCM.swift
- Sources/NIOSSH/TransportProtection/SSHTransportProtection.swift
- Tests/NIOSSHTests/AESGCMTests.swift
- Tests/NIOSSHTests/SSHKeyExchangeStateMachineTests.swift
- Tests/NIOSSHTests/SSHPackerSerializerTests.swift
- Tests/NIOSSHTests/SSHPacketParserTests.swift
- Tests/NIOSSHTests/Utilities.swift
- Tests/NIOSSHTests/UtilitiesTests.swift
Motivation:
In some cases AES GCM might not be supported by a server/client, and
clients might require custom algorithms to be implemented in their
projects.
Modifications:
- Makes NIOSSHTransportProtection, NIOSSHSessionKeys and ExpectedKeySizes public
- Makes transport algorithms list configurable
- Adds sequence number of incoming and outgoing messages to parser and
serializer
- Tests
> Adds support for custom transport protection algorithms

- Tests/NIOSSHTests/SSHEncryptedTrafficTests.swift
- Tests/NIOSSHTests/SSHKeyExchangeStateMachineTests.swift
- Tests/NIOSSHTests/SSHPackerSerializerTests.swift
- Tests/NIOSSHTests/SSHPacketParserTests.swift
- Tests/NIOSSHTests/Utilities.swift
Motivation:
#fileID introduced in Swift 5.3, so no longer need to use #file anywhere
Modifications:
Changed #file to #filePath or #fileID depending on the situation
> Use #fileID/#filePath instead of #file

- Sources/NIOSSH/SSHPacketSerializer.swift
- Sources/NIOSSH/TransportProtection/AESGCM.swift
- Sources/NIOSSH/TransportProtection/SSHTransportProtection.swift
- Tests/NIOSSHTests/AESGCMTests.swift
- Tests/NIOSSHTests/SSHKeyExchangeStateMachineTests.swift
- Tests/NIOSSHTests/SSHPacketParserTests.swift
- Tests/NIOSSHTests/Utilities.swift
- Tests/NIOSSHTests/UtilitiesTests.swift
Motivation:
I think there is a bit of a mix of responsibilities between TransportProtection and PacketSerializer. PacketSerializer is responsible for writing out plaintext packet structure, but encrypted packet structure is written out by the TransportProtection implementations. This means that we will have duplicate implementations of basic packet writing logic, every implementation of TP will have to write length, padding length, payload and padding. Also, right now this API uses EncryptablePayload, which we cannot make fully public and accessible for writing tests as it will mean making all SSHMessages public as well.
Modifications:
- Extract packet writing logic to a separate function that will be used by both plaintext and ciphertext modes
- Removes usage of EncryptablePayload
- …
> Refactoring of the encryptPacket method

- IntegrationTests/plugin_echo.sh
- IntegrationTests/plugin_junit_xml.sh
- IntegrationTests/run-single-test.sh
- IntegrationTests/run-tests.sh
- IntegrationTests/test_functions.sh
- IntegrationTests/tests_01_allocation_counters/defines.sh
- IntegrationTests/tests_01_allocation_counters/test_01_allocation_counts.sh
- IntegrationTests/tests_01_allocation_counters/test_01_resources/run-nio-ssh-alloc-counter-tests.sh
- IntegrationTests/tests_01_allocation_counters/test_01_resources/shared.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_many_small_commands_per_connection.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_one_command_per_connection.swift
- IntegrationTests/tests_01_allocation_counters/test_01_resources/test_client_server_streaming_large_message_in_small_chunks.swift
- dev/alloc-limits-from-test-output
- dev/update-alloc-limits-to-last-completed-ci-build
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.main.yaml
- docker/docker-compose.yaml
- scripts/integration_tests.sh
- scripts/soundness.sh
Motivation:
Having bumped into a missed CoW, having the allocation counter tests will be a useful way to validate when we hit and fix them.
Modifications:
- Add the alloc counter framework from NIO
- Add three test cases
- Add the CI hooks for the alloc counters
Result:
We'll have allocation counter tests
> Add iniital allocation counter tests for SSH

- Sources/NIOSSH/Connection State Machine/SSHConnectionStateMachine.swift
- Sources/NIOSSH/Connection State Machine/States/ActiveState.swift
- Sources/NIOSSH/Connection State Machine/States/KeyExchangeState.swift
- Sources/NIOSSH/Connection State Machine/States/ReceivedKexInitWhenActiveState.swift
- Sources/NIOSSH/Connection State Machine/States/ReceivedNewKeysState.swift
- Sources/NIOSSH/Connection State Machine/States/RekeyingReceivedNewKeysState.swift
- Sources/NIOSSH/Connection State Machine/States/RekeyingSentNewKeysState.swift
- Sources/NIOSSH/Connection State Machine/States/RekeyingState.swift
- Sources/NIOSSH/Connection State Machine/States/SentKexInitWhenActiveState.swift
- Sources/NIOSSH/Connection State Machine/States/SentNewKeysState.swift
- Sources/NIOSSH/Connection State Machine/States/SentVersionState.swift
- Sources/NIOSSH/Connection State Machine/States/UserAuthenticationState.swift
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.main.yaml
Motivation
CoW on the datapath is really gnarly, and we'd like to avoid it if at all possible.
Modifications
- Move some methods into mutating funcs on the state enum, which lets the compiler elide a retain/release pair that force a CoW
- Add proper reset code to a function that throws to ensure that the compiler can see that the state is always restored afterward.
Results
Drastically lowered allocation count
> Remove some data-path CoW

- Sources/NIOSSHClient/InteractivePasswordPromptDelegate.swift
Android doesn't have `getpass()` either.
@Joannis, submitted as you asked for.
> Add Android support

- docker/docker-compose.2204.main.yaml
Swift appears to have regressed allocations in the nightlies. I don't know why yet, but for now let's get CI working again.
> Update allocation limits for main vs 5.8

- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
- Tests/NIOSSHTests/ChildChannelMultiplexerTests.swift
Motivation:
Currently the library crashes if a window update is required and the connection is closed locally.
Modifications:
Check the connection state before sending a window update message.
> Avoid sending window update messages if locally closed (#143)

- docker/docker-compose.2004.56.yaml
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.59.yaml
- docker/docker-compose.2204.main.yaml
Allocations regressed due to our use of EmbeddedChannel, which now uses a new atomic since apple/swift-nio#2429. We can update the limits accordingly.
> Update allocation limits

- Sources/NIOSSH/ByteBuffer+SSH.swift
- Sources/NIOSSH/SSHPacketSerializer.swift
- Tests/NIOSSHTests/ByteBuffer+SSHTests.swift
Motivation:
In two different places in this module we "reserve" space by moving the writer index forward. This isn't the correct way to do that, and it's a bit of a needless performance
optimization. Instead, just write a zero in that location and come back to it.
Modifications:
- Replace unmotivated writer index move with a write.
- Add tests.
Result:
Fewer crashes
> Correctly resize ByteBuffers

- Sources/NIOSSH/Connection State Machine/States/SentVersionState.swift
- Sources/NIOSSH/SSHPacketParser.swift
- Sources/NIOSSHClient/ExecHandler.swift
- Sources/NIOSSHServer/ExecHandler.swift
- Tests/NIOSSHTests/SSHEncryptedTrafficTests.swift
- Tests/NIOSSHTests/SSHPackerSerializerTests.swift
- Tests/NIOSSHTests/SSHPacketParserTests.swift
Motivation:
Server may send additional lines of data before version, but since we use version as part of key exchange, we need to filter out those lines, otherwise it will fail key exchange.
Modifications:
- Strip out lines of data before version in client role
- Update tests
> Fixes client mode version parsing

- Sources/NIOSSHPerformanceTester/Benchmark.swift
- Sources/NIOSSHPerformanceTester/main.swift
- Tests/NIOSSHTests/ChildChannelMultiplexerTests.swift
- Tests/NIOSSHTests/EndToEndTests.swift
- Tests/NIOSSHTests/SSHKeyExchangeStateMachineTests.swift
Motivation:
Swift concurrency warnings are here to help.
We can encode some of our assumptions to the type system.
Modifications:
Replace a number of captured variables with LoopBound instances.
Result:
Fewer sendability warnings
> Fix some sendability warnings in tests

- docker/docker-compose.2204.59.yaml
- docker/docker-compose.2204.main.yaml
While we should investigate why these regressed, for now let's unblock development.
> Update allocation results

- Sources/NIOSSH/SSHMessages.swift
- docker/docker-compose.2204.510.yaml
- docker/docker-compose.2204.57.yaml
- docker/docker-compose.2204.58.yaml
- docker/docker-compose.2204.59.yaml
- docker/docker-compose.2204.main.yaml
The specialization for `[Substring].joined` was dropped in Swift 5.9[^1] and consequently we regressed in allocations[^2].
Workaround the lack of specialized `[Substring].joined` by handwriting the comma-separated concatenation of the SSH algorithms.
Reduces the allocations to below what they were prior to the toolchain regression.
As a baseline, I was using `d23c142` of this repo, which is a commit from around the time of the toolchain regression.
The allocation results are as follows:
| swift-nio-ssh     | swift toolchain  | allocs    |
|------------------:|:-----------------|----------:|
| d23c142 (Aug 11)  | 5.9-2023-07-25   | 1,007,000 |
|                   | 5.9-2023-07-29   | 1,100,000 |
|                   | 5.9-RELEASE       | 1,100,000 |
| d23c142 + patch   | 5.9-2023-07-25   | …
> Workaround allocation regression caused by missing specialized `[Substring].joined`

- Sources/NIOSSHClient/ExecHandler.swift
Motivation:
Get this repo building with Android NDK 26, [which added nullability annotations](https://android.googlesource.com/platform/bionic/+/00a3dbaab65a7d628312fd67099c662942b1d45f%5E%21/#F0)
Modifications:
- A single force unwrap of a buffer's `baseAddress`
Result:
This repo builds and passes its tests with the latest Android LTS NDK 26.
I made sure this pull doesn't break anything by testing it on linux x86_64 and with the previous NDK 25c too. I used this patch with others to build the Swift toolchain and this package for my Android CI, finagolfin/swift-android-sdk#122.
> Android: force unwrap address passed to fwrite() for NDK 26

- Sources/NIOSSHServer/DataToBufferCodec.swift
- Sources/NIOSSHServer/ExecHandler.swift
- Sources/NIOSSHServer/GlueHandler.swift
- Sources/NIOSSHServer/RemotePortForwarding.swift
- Sources/NIOSSHServer/main.swift
- Tests/NIOSSHTests/SSHConnectionStateMachineTests.swift
- Tests/NIOSSHTests/SSHPackerSerializerTests.swift
- Tests/NIOSSHTests/SSHPacketParserTests.swift
- Tests/NIOSSHTests/Utilities.swift
- Tests/NIOSSHTests/UtilitiesTests.swift
When building this project for Apple platforms other than macOS, the build failed for a couple of reasons. First, `NIOSSHServer` requires `Foundation.Process` which is only available on macOS. Second, the tests are making use of an CryptoKit API that's only present on iOS 13.2 (and aligned other versions), which is newer than the 13.0 stated in the Package.swift:
```
error: Cannot find type 'Process' in scope
...
error: 'isValidAuthenticationCode(_:authenticating:using:)' is only available in iOS 13.2 or newer
```
- Wrap all the code in `NIOSSHServer` with `#if canImport(Foundation.Process)` and, in `main.swift`, throw a `fatalError` with a helpful message.
- Add missing availability guards in test code. I've tried to keep them as scoped as possible.
Source and tests can now build on …
> Fix build on non-macOS Apple platforms

- Sources/NIOSSH/Keys And Signatures/NIOSSHCertifiedPublicKey.swift
Swift 6 has switched to this new Android overlay, swiftlang/swift#74758, which I've been testing on this repo without a problem using my daily Android CI for weeks now, finagolfin/swift-android-sdk#151.
> Use Bionic module from new Android overlay in Swift 6 instead

- .github/workflows/main.yml
* `main.yml` and `scheduled.yml` are mostly duplicative.
* Scheduled runs failed because of a deprecated reference to a Swift 5.8 pipeline
* Unify `main.yml` and `scheduled.yml`
* Remove the reference to the 5.8 pipeline
Working scheduled runs.
> Unify main.yml and scheduled.yml, remove 5_8 ref

- Package.swift
- Sources/NIOSSH/Connection State Machine/Operations/AcceptsUserAuthMessages.swift
- Sources/NIOSSH/Key Exchange/EllipticCurveKeyExchange.swift
- Sources/NIOSSH/Keys And Signatures/NIOSSHCertifiedPublicKey.swift
- Sources/NIOSSH/Keys And Signatures/NIOSSHPrivateKey.swift
- Sources/NIOSSH/Keys And Signatures/NIOSSHPublicKey.swift
- Sources/NIOSSHPerformanceTester/BenchmarkHandshake.swift
- Sources/NIOSSHPerformanceTester/BenchmarkLinearThroughput.swift
- Tests/NIOSSHTests/HostKeyTests.swift
Enable MemberImportVisibility check on all targets. Use a standard string header and footer to bracket the new block for ease of updating in the future with scripts.
> Enable MemberImportVisibility check on all targets

- Sources/NIOSSH/Keys And Signatures/NIOSSHCertifiedPublicKey.swift
Motivation:
It turns out that #183 broke the build on a number of platforms, including Linux 6.1+, Android 6.1+, and on 6.0 macOS. We need to keep things building.
Modifications:
Guard the import of CDispatch
Remove the use of replacingOccurrences
Result:
Better builds.
> Fix build on all platforms

- Tests/NIOSSHTests/EndToEndTests.swift
Motivation:
Some tests rely on extracting the server handler from a channel pipeline. There's a typo here where the handler is pulled from the client channel, meaning its client handler not the server handler.
Modifications:
- Get the server handler from the server channel
Result:
Tests still pass
> Get handler from correct channel in tests

- Package.swift
- Sources/NIOSSH/Child Channels/ChildChannelOptions.swift
- Sources/NIOSSH/Child Channels/ChildChannelUserEvents.swift
- Sources/NIOSSH/Child Channels/SSHChildChannel.swift
- Sources/NIOSSH/GlobalRequestDelegate.swift
- Sources/NIOSSH/NIOSSHHandler.swift
- Sources/NIOSSH/Role.swift
- Sources/NIOSSH/SSHClientConfiguration.swift
- Sources/NIOSSH/SSHServerConfiguration.swift
- Sources/NIOSSH/User Authentication/ClientUserAuthenticationDelegate.swift
Modifications:
- Add missing explicit annotations
- Use `any Sendable` rather than `Any` when dealing with user events internally
- Use the isolated event loop where necessary
- Fix a typo
> Strict concurrency for NIOSSH

- Sources/NIOSSH/Child Channels/SSHChannelData.swift
Motivation:
Since IOData now sendable we can mark SSHChannel data sendable as well. This is required if we want to wrap SSH channel in a NIOAsyncChannel that operates with SSHChannelData
Modifications:
- Remove unavailable from sendable conformance
Result:
- SSHChannelData is now sendable
> Marks SSHChannelData as sendable

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- Sources/NIOSSHClient/ExecHandler.swift
Re-enable warnings-as-errors on Swift 6.0 now that strict concurrency issues have been resolved.
> Re-enable warnings-as-errors on Swift 6.0

- Package.swift
Add "-Xfrontend" to strict concurrency settings `-require-explicit-sendable` flag, it doesn't seem to work consistently without it.
> Add "-Xfrontend" to strict concurrency settings

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- Benchmarks/Package.swift
- Benchmarks/Thresholds/5.9/NIOSSHBenchmarks.ManySmallCommandsPerConnection.p90.json
- Benchmarks/Thresholds/5.9/NIOSSHBenchmarks.OneCommandPerConnection.p90.json
- Benchmarks/Thresholds/5.9/NIOSSHBenchmarks.StreamingLargeMessageInSmallChunks.p90.json
- Package.swift
- README.md
Motivation:
Swift 5.9 is no longer supported, we should bump the tools version and remove it from our CI.
Modifications:
* Bump the Swift tools version to Swift 5.10
* Remove Swift 5.9 jobs where appropriate in main.yml, pull_request.yml
Result:
Code reflects our support window.
> Drop Swift 5.9

- Benchmarks/Thresholds/nightly-next/NIOSSHBenchmarks.ManySmallCommandsPerConnection.p90.json
- Benchmarks/Thresholds/nightly-next/NIOSSHBenchmarks.OneCommandPerConnection.p90.json
- Benchmarks/Thresholds/nightly-next/NIOSSHBenchmarks.StreamingLargeMessageInSmallChunks.p90.json
Switching nightly-next to 6.2 nightlies lowered allocations in one of the benchmarks.
Update the benchmark thresholds.
Benchmarks checks for nightly-next pass.
> Update nightly-next thresholds to lock in wins
